// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryProtocol.proto

package com.khalifa.protocol;

public final class QueryProtocol {
  private QueryProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STRING = 0;</code>
     */
    STRING(0, 0),
    /**
     * <code>SHORT = 1;</code>
     */
    SHORT(1, 1),
    /**
     * <code>INTEGER = 2;</code>
     */
    INTEGER(2, 2),
    /**
     * <code>LONG = 3;</code>
     */
    LONG(3, 3),
    /**
     * <code>FLOAT = 4;</code>
     */
    FLOAT(4, 4),
    /**
     * <code>DOUBLE = 5;</code>
     */
    DOUBLE(5, 5),
    /**
     * <code>DATE = 6;</code>
     */
    DATE(6, 6),
    /**
     * <code>TIME = 7;</code>
     */
    TIME(7, 7),
    /**
     * <code>TIMESTAMP = 8;</code>
     */
    TIMESTAMP(8, 8),
    ;

    /**
     * <code>STRING = 0;</code>
     */
    public static final int STRING_VALUE = 0;
    /**
     * <code>SHORT = 1;</code>
     */
    public static final int SHORT_VALUE = 1;
    /**
     * <code>INTEGER = 2;</code>
     */
    public static final int INTEGER_VALUE = 2;
    /**
     * <code>LONG = 3;</code>
     */
    public static final int LONG_VALUE = 3;
    /**
     * <code>FLOAT = 4;</code>
     */
    public static final int FLOAT_VALUE = 4;
    /**
     * <code>DOUBLE = 5;</code>
     */
    public static final int DOUBLE_VALUE = 5;
    /**
     * <code>DATE = 6;</code>
     */
    public static final int DATE_VALUE = 6;
    /**
     * <code>TIME = 7;</code>
     */
    public static final int TIME_VALUE = 7;
    /**
     * <code>TIMESTAMP = 8;</code>
     */
    public static final int TIMESTAMP_VALUE = 8;


    public final int getNumber() { return value; }

    public static DataType valueOf(int value) {
      switch (value) {
        case 0: return STRING;
        case 1: return SHORT;
        case 2: return INTEGER;
        case 3: return LONG;
        case 4: return FLOAT;
        case 5: return DOUBLE;
        case 6: return DATE;
        case 7: return TIME;
        case 8: return TIMESTAMP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.khalifa.protocol.QueryProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DataType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DataType)
  }

  public interface QueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 queryType = 1;
    /**
     * <code>required int32 queryType = 1;</code>
     */
    boolean hasQueryType();
    /**
     * <code>required int32 queryType = 1;</code>
     */
    int getQueryType();

    // required string dbname = 2;
    /**
     * <code>required string dbname = 2;</code>
     */
    boolean hasDbname();
    /**
     * <code>required string dbname = 2;</code>
     */
    java.lang.String getDbname();
    /**
     * <code>required string dbname = 2;</code>
     */
    com.google.protobuf.ByteString
        getDbnameBytes();

    // required bytes command = 3;
    /**
     * <code>required bytes command = 3;</code>
     */
    boolean hasCommand();
    /**
     * <code>required bytes command = 3;</code>
     */
    com.google.protobuf.ByteString getCommand();

    // repeated string param = 4;
    /**
     * <code>repeated string param = 4;</code>
     */
    java.util.List<java.lang.String>
    getParamList();
    /**
     * <code>repeated string param = 4;</code>
     */
    int getParamCount();
    /**
     * <code>repeated string param = 4;</code>
     */
    java.lang.String getParam(int index);
    /**
     * <code>repeated string param = 4;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes(int index);

    // repeated bytes value = 5;
    /**
     * <code>repeated bytes value = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getValueList();
    /**
     * <code>repeated bytes value = 5;</code>
     */
    int getValueCount();
    /**
     * <code>repeated bytes value = 5;</code>
     */
    com.google.protobuf.ByteString getValue(int index);

    // repeated .DataType type = 6;
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList();
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    com.khalifa.protocol.QueryProtocol.DataType getType(int index);

    // optional int32 expire = 7;
    /**
     * <code>optional int32 expire = 7;</code>
     */
    boolean hasExpire();
    /**
     * <code>optional int32 expire = 7;</code>
     */
    int getExpire();
  }
  /**
   * Protobuf type {@code Query}
   */
  public static final class Query extends
      com.google.protobuf.GeneratedMessage
      implements QueryOrBuilder {
    // Use Query.newBuilder() to construct.
    private Query(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Query(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Query defaultInstance;
    public static Query getDefaultInstance() {
      return defaultInstance;
    }

    public Query getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              queryType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dbname_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              command_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                param_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              param_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              value_.add(input.readBytes());
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.khalifa.protocol.QueryProtocol.DataType value = com.khalifa.protocol.QueryProtocol.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                  type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>();
                  mutable_bitField0_ |= 0x00000020;
                }
                type_.add(value);
              }
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.khalifa.protocol.QueryProtocol.DataType value = com.khalifa.protocol.QueryProtocol.DataType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(6, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                    type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>();
                    mutable_bitField0_ |= 0x00000020;
                  }
                  type_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 56: {
              bitField0_ |= 0x00000008;
              expire_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          param_ = new com.google.protobuf.UnmodifiableLazyStringList(param_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.khalifa.protocol.QueryProtocol.internal_static_Query_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.khalifa.protocol.QueryProtocol.internal_static_Query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.khalifa.protocol.QueryProtocol.Query.class, com.khalifa.protocol.QueryProtocol.Query.Builder.class);
    }

    public static com.google.protobuf.Parser<Query> PARSER =
        new com.google.protobuf.AbstractParser<Query>() {
      public Query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Query> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 queryType = 1;
    public static final int QUERYTYPE_FIELD_NUMBER = 1;
    private int queryType_;
    /**
     * <code>required int32 queryType = 1;</code>
     */
    public boolean hasQueryType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 queryType = 1;</code>
     */
    public int getQueryType() {
      return queryType_;
    }

    // required string dbname = 2;
    public static final int DBNAME_FIELD_NUMBER = 2;
    private java.lang.Object dbname_;
    /**
     * <code>required string dbname = 2;</code>
     */
    public boolean hasDbname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string dbname = 2;</code>
     */
    public java.lang.String getDbname() {
      java.lang.Object ref = dbname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dbname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDbnameBytes() {
      java.lang.Object ref = dbname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes command = 3;
    public static final int COMMAND_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString command_;
    /**
     * <code>required bytes command = 3;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes command = 3;</code>
     */
    public com.google.protobuf.ByteString getCommand() {
      return command_;
    }

    // repeated string param = 4;
    public static final int PARAM_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList param_;
    /**
     * <code>repeated string param = 4;</code>
     */
    public java.util.List<java.lang.String>
        getParamList() {
      return param_;
    }
    /**
     * <code>repeated string param = 4;</code>
     */
    public int getParamCount() {
      return param_.size();
    }
    /**
     * <code>repeated string param = 4;</code>
     */
    public java.lang.String getParam(int index) {
      return param_.get(index);
    }
    /**
     * <code>repeated string param = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes(int index) {
      return param_.getByteString(index);
    }

    // repeated bytes value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> value_;
    /**
     * <code>repeated bytes value = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated bytes value = 5;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated bytes value = 5;</code>
     */
    public com.google.protobuf.ByteString getValue(int index) {
      return value_.get(index);
    }

    // repeated .DataType type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private java.util.List<com.khalifa.protocol.QueryProtocol.DataType> type_;
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    public java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList() {
      return type_;
    }
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .DataType type = 6;</code>
     */
    public com.khalifa.protocol.QueryProtocol.DataType getType(int index) {
      return type_.get(index);
    }

    // optional int32 expire = 7;
    public static final int EXPIRE_FIELD_NUMBER = 7;
    private int expire_;
    /**
     * <code>optional int32 expire = 7;</code>
     */
    public boolean hasExpire() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 expire = 7;</code>
     */
    public int getExpire() {
      return expire_;
    }

    private void initFields() {
      queryType_ = 0;
      dbname_ = "";
      command_ = com.google.protobuf.ByteString.EMPTY;
      param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      value_ = java.util.Collections.emptyList();
      type_ = java.util.Collections.emptyList();
      expire_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasQueryType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDbname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, queryType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDbnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, command_);
      }
      for (int i = 0; i < param_.size(); i++) {
        output.writeBytes(4, param_.getByteString(i));
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeBytes(5, value_.get(i));
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnum(6, type_.get(i).getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(7, expire_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, queryType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDbnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, command_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < param_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(param_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParamList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(value_.get(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * type_.size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, expire_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.khalifa.protocol.QueryProtocol.Query prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.khalifa.protocol.QueryProtocol.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Query_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.khalifa.protocol.QueryProtocol.Query.class, com.khalifa.protocol.QueryProtocol.Query.Builder.class);
      }

      // Construct using com.khalifa.protocol.QueryProtocol.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        queryType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dbname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        expire_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Query_descriptor;
      }

      public com.khalifa.protocol.QueryProtocol.Query getDefaultInstanceForType() {
        return com.khalifa.protocol.QueryProtocol.Query.getDefaultInstance();
      }

      public com.khalifa.protocol.QueryProtocol.Query build() {
        com.khalifa.protocol.QueryProtocol.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.khalifa.protocol.QueryProtocol.Query buildPartial() {
        com.khalifa.protocol.QueryProtocol.Query result = new com.khalifa.protocol.QueryProtocol.Query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queryType_ = queryType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dbname_ = dbname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.command_ = command_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          param_ = new com.google.protobuf.UnmodifiableLazyStringList(
              param_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.param_ = param_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.value_ = value_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.expire_ = expire_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.khalifa.protocol.QueryProtocol.Query) {
          return mergeFrom((com.khalifa.protocol.QueryProtocol.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.khalifa.protocol.QueryProtocol.Query other) {
        if (other == com.khalifa.protocol.QueryProtocol.Query.getDefaultInstance()) return this;
        if (other.hasQueryType()) {
          setQueryType(other.getQueryType());
        }
        if (other.hasDbname()) {
          bitField0_ |= 0x00000002;
          dbname_ = other.dbname_;
          onChanged();
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (!other.param_.isEmpty()) {
          if (param_.isEmpty()) {
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamIsMutable();
            param_.addAll(other.param_);
          }
          onChanged();
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (other.hasExpire()) {
          setExpire(other.getExpire());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQueryType()) {
          
          return false;
        }
        if (!hasDbname()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.khalifa.protocol.QueryProtocol.Query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.khalifa.protocol.QueryProtocol.Query) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 queryType = 1;
      private int queryType_ ;
      /**
       * <code>required int32 queryType = 1;</code>
       */
      public boolean hasQueryType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 queryType = 1;</code>
       */
      public int getQueryType() {
        return queryType_;
      }
      /**
       * <code>required int32 queryType = 1;</code>
       */
      public Builder setQueryType(int value) {
        bitField0_ |= 0x00000001;
        queryType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 queryType = 1;</code>
       */
      public Builder clearQueryType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        queryType_ = 0;
        onChanged();
        return this;
      }

      // required string dbname = 2;
      private java.lang.Object dbname_ = "";
      /**
       * <code>required string dbname = 2;</code>
       */
      public boolean hasDbname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string dbname = 2;</code>
       */
      public java.lang.String getDbname() {
        java.lang.Object ref = dbname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dbname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dbname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDbnameBytes() {
        java.lang.Object ref = dbname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dbname = 2;</code>
       */
      public Builder setDbname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dbname = 2;</code>
       */
      public Builder clearDbname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dbname_ = getDefaultInstance().getDbname();
        onChanged();
        return this;
      }
      /**
       * <code>required string dbname = 2;</code>
       */
      public Builder setDbnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbname_ = value;
        onChanged();
        return this;
      }

      // required bytes command = 3;
      private com.google.protobuf.ByteString command_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes command = 3;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes command = 3;</code>
       */
      public com.google.protobuf.ByteString getCommand() {
        return command_;
      }
      /**
       * <code>required bytes command = 3;</code>
       */
      public Builder setCommand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes command = 3;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }

      // repeated string param = 4;
      private com.google.protobuf.LazyStringList param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          param_ = new com.google.protobuf.LazyStringArrayList(param_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public java.util.List<java.lang.String>
          getParamList() {
        return java.util.Collections.unmodifiableList(param_);
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public int getParamCount() {
        return param_.size();
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public java.lang.String getParam(int index) {
        return param_.get(index);
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes(int index) {
        return param_.getByteString(index);
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public Builder setParam(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public Builder addParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public Builder addAllParam(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamIsMutable();
        super.addAll(values, param_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public Builder clearParam() {
        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 4;</code>
       */
      public Builder addParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.add(value);
        onChanged();
        return this;
      }

      // repeated bytes value = 5;
      private java.util.List<com.google.protobuf.ByteString> value_ = java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          value_ = new java.util.ArrayList<com.google.protobuf.ByteString>(value_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public com.google.protobuf.ByteString getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public Builder setValue(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public Builder addValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureValueIsMutable();
        super.addAll(values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes value = 5;</code>
       */
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated .DataType type = 6;
      private java.util.List<com.khalifa.protocol.QueryProtocol.DataType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>(type_);
          bitField0_ |= 0x00000020;
        }
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public com.khalifa.protocol.QueryProtocol.DataType getType(int index) {
        return type_.get(index);
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public Builder setType(
          int index, com.khalifa.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public Builder addType(com.khalifa.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends com.khalifa.protocol.QueryProtocol.DataType> values) {
        ensureTypeIsMutable();
        super.addAll(values, type_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 6;</code>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // optional int32 expire = 7;
      private int expire_ ;
      /**
       * <code>optional int32 expire = 7;</code>
       */
      public boolean hasExpire() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 expire = 7;</code>
       */
      public int getExpire() {
        return expire_;
      }
      /**
       * <code>optional int32 expire = 7;</code>
       */
      public Builder setExpire(int value) {
        bitField0_ |= 0x00000040;
        expire_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expire = 7;</code>
       */
      public Builder clearExpire() {
        bitField0_ = (bitField0_ & ~0x00000040);
        expire_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Query)
    }

    static {
      defaultInstance = new Query(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Query)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    // repeated string header = 2;
    /**
     * <code>repeated string header = 2;</code>
     */
    java.util.List<java.lang.String>
    getHeaderList();
    /**
     * <code>repeated string header = 2;</code>
     */
    int getHeaderCount();
    /**
     * <code>repeated string header = 2;</code>
     */
    java.lang.String getHeader(int index);
    /**
     * <code>repeated string header = 2;</code>
     */
    com.google.protobuf.ByteString
        getHeaderBytes(int index);

    // repeated .DataType type = 3;
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList();
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    com.khalifa.protocol.QueryProtocol.DataType getType(int index);

    // repeated bytes data = 4;
    /**
     * <code>repeated bytes data = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDataList();
    /**
     * <code>repeated bytes data = 4;</code>
     */
    int getDataCount();
    /**
     * <code>repeated bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData(int index);
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                header_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              header_.add(input.readBytes());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.khalifa.protocol.QueryProtocol.DataType value = com.khalifa.protocol.QueryProtocol.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>();
                  mutable_bitField0_ |= 0x00000004;
                }
                type_.add(value);
              }
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.khalifa.protocol.QueryProtocol.DataType value = com.khalifa.protocol.QueryProtocol.DataType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>();
                    mutable_bitField0_ |= 0x00000004;
                  }
                  type_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              data_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          header_ = new com.google.protobuf.UnmodifiableLazyStringList(header_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.khalifa.protocol.QueryProtocol.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.khalifa.protocol.QueryProtocol.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.khalifa.protocol.QueryProtocol.Response.class, com.khalifa.protocol.QueryProtocol.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    // repeated string header = 2;
    public static final int HEADER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList header_;
    /**
     * <code>repeated string header = 2;</code>
     */
    public java.util.List<java.lang.String>
        getHeaderList() {
      return header_;
    }
    /**
     * <code>repeated string header = 2;</code>
     */
    public int getHeaderCount() {
      return header_.size();
    }
    /**
     * <code>repeated string header = 2;</code>
     */
    public java.lang.String getHeader(int index) {
      return header_.get(index);
    }
    /**
     * <code>repeated string header = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderBytes(int index) {
      return header_.getByteString(index);
    }

    // repeated .DataType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.util.List<com.khalifa.protocol.QueryProtocol.DataType> type_;
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    public java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList() {
      return type_;
    }
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .DataType type = 3;</code>
     */
    public com.khalifa.protocol.QueryProtocol.DataType getType(int index) {
      return type_.get(index);
    }

    // repeated bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> data_;
    /**
     * <code>repeated bytes data = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bytes data = 4;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }

    private void initFields() {
      code_ = 0;
      header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = java.util.Collections.emptyList();
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      for (int i = 0; i < header_.size(); i++) {
        output.writeBytes(2, header_.getByteString(i));
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnum(3, type_.get(i).getNumber());
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(4, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < header_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(header_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHeaderList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * type_.size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.khalifa.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.khalifa.protocol.QueryProtocol.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.khalifa.protocol.QueryProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.khalifa.protocol.QueryProtocol.Response.class, com.khalifa.protocol.QueryProtocol.Response.Builder.class);
      }

      // Construct using com.khalifa.protocol.QueryProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.khalifa.protocol.QueryProtocol.internal_static_Response_descriptor;
      }

      public com.khalifa.protocol.QueryProtocol.Response getDefaultInstanceForType() {
        return com.khalifa.protocol.QueryProtocol.Response.getDefaultInstance();
      }

      public com.khalifa.protocol.QueryProtocol.Response build() {
        com.khalifa.protocol.QueryProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.khalifa.protocol.QueryProtocol.Response buildPartial() {
        com.khalifa.protocol.QueryProtocol.Response result = new com.khalifa.protocol.QueryProtocol.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          header_ = new com.google.protobuf.UnmodifiableLazyStringList(
              header_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.header_ = header_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.khalifa.protocol.QueryProtocol.Response) {
          return mergeFrom((com.khalifa.protocol.QueryProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.khalifa.protocol.QueryProtocol.Response other) {
        if (other == com.khalifa.protocol.QueryProtocol.Response.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.khalifa.protocol.QueryProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.khalifa.protocol.QueryProtocol.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // repeated string header = 2;
      private com.google.protobuf.LazyStringList header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHeaderIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          header_ = new com.google.protobuf.LazyStringArrayList(header_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public java.util.List<java.lang.String>
          getHeaderList() {
        return java.util.Collections.unmodifiableList(header_);
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public int getHeaderCount() {
        return header_.size();
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public java.lang.String getHeader(int index) {
        return header_.get(index);
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHeaderBytes(int index) {
        return header_.getByteString(index);
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public Builder setHeader(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public Builder addHeader(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public Builder addAllHeader(
          java.lang.Iterable<java.lang.String> values) {
        ensureHeaderIsMutable();
        super.addAll(values, header_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public Builder clearHeader() {
        header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string header = 2;</code>
       */
      public Builder addHeaderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
        return this;
      }

      // repeated .DataType type = 3;
      private java.util.List<com.khalifa.protocol.QueryProtocol.DataType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = new java.util.ArrayList<com.khalifa.protocol.QueryProtocol.DataType>(type_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public java.util.List<com.khalifa.protocol.QueryProtocol.DataType> getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public com.khalifa.protocol.QueryProtocol.DataType getType(int index) {
        return type_.get(index);
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public Builder setType(
          int index, com.khalifa.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public Builder addType(com.khalifa.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends com.khalifa.protocol.QueryProtocol.DataType> values) {
        ensureTypeIsMutable();
        super.addAll(values, type_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .DataType type = 3;</code>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // repeated bytes data = 4;
      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 4;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Query_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Query_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023QueryProtocol.proto\"\202\001\n\005Query\022\021\n\tquery" +
      "Type\030\001 \002(\005\022\016\n\006dbname\030\002 \002(\t\022\017\n\007command\030\003 " +
      "\002(\014\022\r\n\005param\030\004 \003(\t\022\r\n\005value\030\005 \003(\014\022\027\n\004typ" +
      "e\030\006 \003(\0162\t.DataType\022\016\n\006expire\030\007 \001(\005\"O\n\010Re" +
      "sponse\022\014\n\004code\030\001 \002(\005\022\016\n\006header\030\002 \003(\t\022\027\n\004" +
      "type\030\003 \003(\0162\t.DataType\022\014\n\004data\030\004 \003(\014*r\n\010D" +
      "ataType\022\n\n\006STRING\020\000\022\t\n\005SHORT\020\001\022\013\n\007INTEGE" +
      "R\020\002\022\010\n\004LONG\020\003\022\t\n\005FLOAT\020\004\022\n\n\006DOUBLE\020\005\022\010\n\004" +
      "DATE\020\006\022\010\n\004TIME\020\007\022\r\n\tTIMESTAMP\020\010B\'\n\024com.k" +
      "halifa.protocolB\rQueryProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Query_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Query_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Query_descriptor,
              new java.lang.String[] { "QueryType", "Dbname", "Command", "Param", "Value", "Type", "Expire", });
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "Code", "Header", "Type", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
