// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryProtocol.proto

package me.interest.pi.relay.protocol;

public final class QueryProtocol {
  private QueryProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    STRING(0, 0),
    SHORT(1, 1),
    INTEGER(2, 2),
    LONG(3, 3),
    FLOAT(4, 4),
    DOUBLE(5, 5),
    DATE(6, 6),
    TIME(7, 7),
    TIMESTAMP(8, 8),
    ;
    
    public static final int STRING_VALUE = 0;
    public static final int SHORT_VALUE = 1;
    public static final int INTEGER_VALUE = 2;
    public static final int LONG_VALUE = 3;
    public static final int FLOAT_VALUE = 4;
    public static final int DOUBLE_VALUE = 5;
    public static final int DATE_VALUE = 6;
    public static final int TIME_VALUE = 7;
    public static final int TIMESTAMP_VALUE = 8;
    
    
    public final int getNumber() { return value; }
    
    public static DataType valueOf(int value) {
      switch (value) {
        case 0: return STRING;
        case 1: return SHORT;
        case 2: return INTEGER;
        case 3: return LONG;
        case 4: return FLOAT;
        case 5: return DOUBLE;
        case 6: return DATE;
        case 7: return TIME;
        case 8: return TIMESTAMP;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.interest.pi.relay.protocol.QueryProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final DataType[] VALUES = {
      STRING, SHORT, INTEGER, LONG, FLOAT, DOUBLE, DATE, TIME, TIMESTAMP, 
    };
    
    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private DataType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:DataType)
  }
  
  public interface QueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 queryType = 1;
    boolean hasQueryType();
    int getQueryType();
    
    // required string dbname = 2;
    boolean hasDbname();
    String getDbname();
    
    // required bytes command = 4;
    boolean hasCommand();
    com.google.protobuf.ByteString getCommand();
    
    // repeated string param = 5;
    java.util.List<String> getParamList();
    int getParamCount();
    String getParam(int index);
    
    // repeated bytes value = 6;
    java.util.List<com.google.protobuf.ByteString> getValueList();
    int getValueCount();
    com.google.protobuf.ByteString getValue(int index);
    
    // repeated .DataType type = 7;
    java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList();
    int getTypeCount();
    me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index);
    
    // optional int32 expire = 8;
    boolean hasExpire();
    int getExpire();
  }
  public static final class Query extends
      com.google.protobuf.GeneratedMessage
      implements QueryOrBuilder {
    // Use Query.newBuilder() to construct.
    private Query(Builder builder) {
      super(builder);
    }
    private Query(boolean noInit) {}
    
    private static final Query defaultInstance;
    public static Query getDefaultInstance() {
      return defaultInstance;
    }
    
    public Query getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Query_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Query_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 queryType = 1;
    public static final int QUERYTYPE_FIELD_NUMBER = 1;
    private int queryType_;
    public boolean hasQueryType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getQueryType() {
      return queryType_;
    }
    
    // required string dbname = 2;
    public static final int DBNAME_FIELD_NUMBER = 2;
    private java.lang.Object dbname_;
    public boolean hasDbname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDbname() {
      java.lang.Object ref = dbname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dbname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDbnameBytes() {
      java.lang.Object ref = dbname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dbname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes command = 4;
    public static final int COMMAND_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getCommand() {
      return command_;
    }
    
    // repeated string param = 5;
    public static final int PARAM_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList param_;
    public java.util.List<String>
        getParamList() {
      return param_;
    }
    public int getParamCount() {
      return param_.size();
    }
    public String getParam(int index) {
      return param_.get(index);
    }
    
    // repeated bytes value = 6;
    public static final int VALUE_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> value_;
    public java.util.List<com.google.protobuf.ByteString>
        getValueList() {
      return value_;
    }
    public int getValueCount() {
      return value_.size();
    }
    public com.google.protobuf.ByteString getValue(int index) {
      return value_.get(index);
    }
    
    // repeated .DataType type = 7;
    public static final int TYPE_FIELD_NUMBER = 7;
    private java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> type_;
    public java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList() {
      return type_;
    }
    public int getTypeCount() {
      return type_.size();
    }
    public me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index) {
      return type_.get(index);
    }
    
    // optional int32 expire = 8;
    public static final int EXPIRE_FIELD_NUMBER = 8;
    private int expire_;
    public boolean hasExpire() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getExpire() {
      return expire_;
    }
    
    private void initFields() {
      queryType_ = 0;
      dbname_ = "";
      command_ = com.google.protobuf.ByteString.EMPTY;
      param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      value_ = java.util.Collections.emptyList();;
      type_ = java.util.Collections.emptyList();
      expire_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasQueryType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDbname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, queryType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDbnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, command_);
      }
      for (int i = 0; i < param_.size(); i++) {
        output.writeBytes(5, param_.getByteString(i));
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeBytes(6, value_.get(i));
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnum(7, type_.get(i).getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(8, expire_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, queryType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDbnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, command_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < param_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(param_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParamList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(value_.get(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * type_.size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, expire_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.interest.pi.relay.protocol.QueryProtocol.Query prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.interest.pi.relay.protocol.QueryProtocol.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Query_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Query_fieldAccessorTable;
      }
      
      // Construct using me.interest.pi.relay.protocol.QueryProtocol.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        queryType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dbname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        expire_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.interest.pi.relay.protocol.QueryProtocol.Query.getDescriptor();
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Query getDefaultInstanceForType() {
        return me.interest.pi.relay.protocol.QueryProtocol.Query.getDefaultInstance();
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Query build() {
        me.interest.pi.relay.protocol.QueryProtocol.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private me.interest.pi.relay.protocol.QueryProtocol.Query buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        me.interest.pi.relay.protocol.QueryProtocol.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Query buildPartial() {
        me.interest.pi.relay.protocol.QueryProtocol.Query result = new me.interest.pi.relay.protocol.QueryProtocol.Query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queryType_ = queryType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dbname_ = dbname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.command_ = command_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          param_ = new com.google.protobuf.UnmodifiableLazyStringList(
              param_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.param_ = param_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.value_ = value_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.expire_ = expire_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.interest.pi.relay.protocol.QueryProtocol.Query) {
          return mergeFrom((me.interest.pi.relay.protocol.QueryProtocol.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.interest.pi.relay.protocol.QueryProtocol.Query other) {
        if (other == me.interest.pi.relay.protocol.QueryProtocol.Query.getDefaultInstance()) return this;
        if (other.hasQueryType()) {
          setQueryType(other.getQueryType());
        }
        if (other.hasDbname()) {
          setDbname(other.getDbname());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (!other.param_.isEmpty()) {
          if (param_.isEmpty()) {
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamIsMutable();
            param_.addAll(other.param_);
          }
          onChanged();
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (other.hasExpire()) {
          setExpire(other.getExpire());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasQueryType()) {
          
          return false;
        }
        if (!hasDbname()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              queryType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dbname_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              command_ = input.readBytes();
              break;
            }
            case 42: {
              ensureParamIsMutable();
              param_.add(input.readBytes());
              break;
            }
            case 50: {
              ensureValueIsMutable();
              value_.add(input.readBytes());
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              me.interest.pi.relay.protocol.QueryProtocol.DataType value = me.interest.pi.relay.protocol.QueryProtocol.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                addType(value);
              }
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                me.interest.pi.relay.protocol.QueryProtocol.DataType value = me.interest.pi.relay.protocol.QueryProtocol.DataType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(7, rawValue);
                } else {
                  addType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              expire_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 queryType = 1;
      private int queryType_ ;
      public boolean hasQueryType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getQueryType() {
        return queryType_;
      }
      public Builder setQueryType(int value) {
        bitField0_ |= 0x00000001;
        queryType_ = value;
        onChanged();
        return this;
      }
      public Builder clearQueryType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        queryType_ = 0;
        onChanged();
        return this;
      }
      
      // required string dbname = 2;
      private java.lang.Object dbname_ = "";
      public boolean hasDbname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDbname() {
        java.lang.Object ref = dbname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dbname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDbname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbname_ = value;
        onChanged();
        return this;
      }
      public Builder clearDbname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dbname_ = getDefaultInstance().getDbname();
        onChanged();
        return this;
      }
      void setDbname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        dbname_ = value;
        onChanged();
      }
      
      // required bytes command = 4;
      private com.google.protobuf.ByteString command_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getCommand() {
        return command_;
      }
      public Builder setCommand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      
      // repeated string param = 5;
      private com.google.protobuf.LazyStringList param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          param_ = new com.google.protobuf.LazyStringArrayList(param_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getParamList() {
        return java.util.Collections.unmodifiableList(param_);
      }
      public int getParamCount() {
        return param_.size();
      }
      public String getParam(int index) {
        return param_.get(index);
      }
      public Builder setParam(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParam(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParam(
          java.lang.Iterable<String> values) {
        ensureParamIsMutable();
        super.addAll(values, param_);
        onChanged();
        return this;
      }
      public Builder clearParam() {
        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addParam(com.google.protobuf.ByteString value) {
        ensureParamIsMutable();
        param_.add(value);
        onChanged();
      }
      
      // repeated bytes value = 6;
      private java.util.List<com.google.protobuf.ByteString> value_ = java.util.Collections.emptyList();;
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          value_ = new java.util.ArrayList<com.google.protobuf.ByteString>(value_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      public int getValueCount() {
        return value_.size();
      }
      public com.google.protobuf.ByteString getValue(int index) {
        return value_.get(index);
      }
      public Builder setValue(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureValueIsMutable();
        super.addAll(values, value_);
        onChanged();
        return this;
      }
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      
      // repeated .DataType type = 7;
      private java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          type_ = new java.util.ArrayList<me.interest.pi.relay.protocol.QueryProtocol.DataType>(type_);
          bitField0_ |= 0x00000020;
        }
      }
      public java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      public int getTypeCount() {
        return type_.size();
      }
      public me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index) {
        return type_.get(index);
      }
      public Builder setType(
          int index, me.interest.pi.relay.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addType(me.interest.pi.relay.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllType(
          java.lang.Iterable<? extends me.interest.pi.relay.protocol.QueryProtocol.DataType> values) {
        ensureTypeIsMutable();
        super.addAll(values, type_);
        onChanged();
        return this;
      }
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      
      // optional int32 expire = 8;
      private int expire_ ;
      public boolean hasExpire() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getExpire() {
        return expire_;
      }
      public Builder setExpire(int value) {
        bitField0_ |= 0x00000040;
        expire_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpire() {
        bitField0_ = (bitField0_ & ~0x00000040);
        expire_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Query)
    }
    
    static {
      defaultInstance = new Query(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Query)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 code = 1;
    boolean hasCode();
    int getCode();
    
    // repeated string header = 2;
    java.util.List<String> getHeaderList();
    int getHeaderCount();
    String getHeader(int index);
    
    // repeated .DataType type = 3;
    java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList();
    int getTypeCount();
    me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index);
    
    // repeated bytes data = 4;
    java.util.List<com.google.protobuf.ByteString> getDataList();
    int getDataCount();
    com.google.protobuf.ByteString getData(int index);
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCode() {
      return code_;
    }
    
    // repeated string header = 2;
    public static final int HEADER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList header_;
    public java.util.List<String>
        getHeaderList() {
      return header_;
    }
    public int getHeaderCount() {
      return header_.size();
    }
    public String getHeader(int index) {
      return header_.get(index);
    }
    
    // repeated .DataType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> type_;
    public java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList() {
      return type_;
    }
    public int getTypeCount() {
      return type_.size();
    }
    public me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index) {
      return type_.get(index);
    }
    
    // repeated bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> data_;
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    public int getDataCount() {
      return data_.size();
    }
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }
    
    private void initFields() {
      code_ = 0;
      header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = java.util.Collections.emptyList();
      data_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      for (int i = 0; i < header_.size(); i++) {
        output.writeBytes(2, header_.getByteString(i));
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnum(3, type_.get(i).getNumber());
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(4, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < header_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(header_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHeaderList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * type_.size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.interest.pi.relay.protocol.QueryProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.interest.pi.relay.protocol.QueryProtocol.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.interest.pi.relay.protocol.QueryProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.interest.pi.relay.protocol.QueryProtocol.internal_static_Response_fieldAccessorTable;
      }
      
      // Construct using me.interest.pi.relay.protocol.QueryProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.interest.pi.relay.protocol.QueryProtocol.Response.getDescriptor();
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Response getDefaultInstanceForType() {
        return me.interest.pi.relay.protocol.QueryProtocol.Response.getDefaultInstance();
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Response build() {
        me.interest.pi.relay.protocol.QueryProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private me.interest.pi.relay.protocol.QueryProtocol.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        me.interest.pi.relay.protocol.QueryProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public me.interest.pi.relay.protocol.QueryProtocol.Response buildPartial() {
        me.interest.pi.relay.protocol.QueryProtocol.Response result = new me.interest.pi.relay.protocol.QueryProtocol.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          header_ = new com.google.protobuf.UnmodifiableLazyStringList(
              header_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.header_ = header_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.interest.pi.relay.protocol.QueryProtocol.Response) {
          return mergeFrom((me.interest.pi.relay.protocol.QueryProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.interest.pi.relay.protocol.QueryProtocol.Response other) {
        if (other == me.interest.pi.relay.protocol.QueryProtocol.Response.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              ensureHeaderIsMutable();
              header_.add(input.readBytes());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              me.interest.pi.relay.protocol.QueryProtocol.DataType value = me.interest.pi.relay.protocol.QueryProtocol.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                addType(value);
              }
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                me.interest.pi.relay.protocol.QueryProtocol.DataType value = me.interest.pi.relay.protocol.QueryProtocol.DataType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  addType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 34: {
              ensureDataIsMutable();
              data_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 code = 1;
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string header = 2;
      private com.google.protobuf.LazyStringList header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHeaderIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          header_ = new com.google.protobuf.LazyStringArrayList(header_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getHeaderList() {
        return java.util.Collections.unmodifiableList(header_);
      }
      public int getHeaderCount() {
        return header_.size();
      }
      public String getHeader(int index) {
        return header_.get(index);
      }
      public Builder setHeader(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addHeader(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllHeader(
          java.lang.Iterable<String> values) {
        ensureHeaderIsMutable();
        super.addAll(values, header_);
        onChanged();
        return this;
      }
      public Builder clearHeader() {
        header_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addHeader(com.google.protobuf.ByteString value) {
        ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
      }
      
      // repeated .DataType type = 3;
      private java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = new java.util.ArrayList<me.interest.pi.relay.protocol.QueryProtocol.DataType>(type_);
          bitField0_ |= 0x00000004;
        }
      }
      public java.util.List<me.interest.pi.relay.protocol.QueryProtocol.DataType> getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      public int getTypeCount() {
        return type_.size();
      }
      public me.interest.pi.relay.protocol.QueryProtocol.DataType getType(int index) {
        return type_.get(index);
      }
      public Builder setType(
          int index, me.interest.pi.relay.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addType(me.interest.pi.relay.protocol.QueryProtocol.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllType(
          java.lang.Iterable<? extends me.interest.pi.relay.protocol.QueryProtocol.DataType> values) {
        ensureTypeIsMutable();
        super.addAll(values, type_);
        onChanged();
        return this;
      }
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // repeated bytes data = 4;
      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      public int getDataCount() {
        return data_.size();
      }
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Query_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Query_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023QueryProtocol.proto\"\202\001\n\005Query\022\021\n\tquery" +
      "Type\030\001 \002(\005\022\016\n\006dbname\030\002 \002(\t\022\017\n\007command\030\004 " +
      "\002(\014\022\r\n\005param\030\005 \003(\t\022\r\n\005value\030\006 \003(\014\022\027\n\004typ" +
      "e\030\007 \003(\0162\t.DataType\022\016\n\006expire\030\010 \001(\005\"O\n\010Re" +
      "sponse\022\014\n\004code\030\001 \002(\005\022\016\n\006header\030\002 \003(\t\022\027\n\004" +
      "type\030\003 \003(\0162\t.DataType\022\014\n\004data\030\004 \003(\014*r\n\010D" +
      "ataType\022\n\n\006STRING\020\000\022\t\n\005SHORT\020\001\022\013\n\007INTEGE" +
      "R\020\002\022\010\n\004LONG\020\003\022\t\n\005FLOAT\020\004\022\n\n\006DOUBLE\020\005\022\010\n\004" +
      "DATE\020\006\022\010\n\004TIME\020\007\022\r\n\tTIMESTAMP\020\010B!\n\035me.in" +
      "terest.pi.relay.protocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Query_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Query_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Query_descriptor,
              new java.lang.String[] { "QueryType", "Dbname", "Command", "Param", "Value", "Type", "Expire", },
              me.interest.pi.relay.protocol.QueryProtocol.Query.class,
              me.interest.pi.relay.protocol.QueryProtocol.Query.Builder.class);
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "Code", "Header", "Type", "Data", },
              me.interest.pi.relay.protocol.QueryProtocol.Response.class,
              me.interest.pi.relay.protocol.QueryProtocol.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
